version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/start-reload.sh"]
    volumes:
      - "./app/api:/app/api"
      - "./app/models:/app/models"
      - "./app/service:/app/service"
    ports:
      - 8080:8080