apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: entro-haystack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: entro-haystack
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50